# Generated by Django 3.1.7 on 2021-03-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_title', models.CharField(max_length=50)),
                ('e_description', models.CharField(max_length=500)),
                ('e_date', models.CharField(max_length=50)),
                ('e_fromTime', models.CharField(max_length=50)),
                ('e_toTime', models.CharField(max_length=50)),
                ('e_created_at', models.DateTimeField(auto_now_add=True)),
                ('e_updated_at', models.DateTimeField(auto_now=True)),
                ('e_postedBy', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeNo', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('job_profession', models.CharField(max_length=30)),
                ('job_address', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('bloodgroup', models.CharField(max_length=20)),
                ('family_member_detail', models.CharField(max_length=20)),
                ('contactNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=30)),
                ('lname', models.CharField(blank=True, max_length=30)),
                ('contact_no', models.CharField(blank=True, max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(blank=True, default='member_default_pic.jpg', upload_to='img/')),
                ('m_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetail')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(blank=True, default='c_profilePic.jpg', upload_to='img/')),
                ('m_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
    ]
