# Generated by Django 3.1.7 on 2021-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0006_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='postedBy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
