# Generated by Django 3.1.7 on 2021-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0007_complaint_postedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='postedBy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
