# Generated by Django 3.1.7 on 2021-04-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0009_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='postedBy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
