# Generated by Django 3.1.7 on 2021-04-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0013_watchman_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchman',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
