# Generated by Django 3.1.7 on 2021-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0014_watchman_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=30)),
                ('lname', models.CharField(blank=True, max_length=30)),
                ('contact_no', models.CharField(blank=True, max_length=30)),
                ('homeNo', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('fromTime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
