# Generated by Django 3.1.7 on 2021-04-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0015_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='fromTime',
            new_name='inTime',
        ),
    ]
