# Generated by Django 3.1.7 on 2021-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0017_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='m_id',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='homeNo',
            field=models.CharField(default='XXX', max_length=20),
        ),
    ]
