# Generated by Django 3.1.7 on 2021-04-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0018_auto_20210410_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
