# Generated by Django 3.1.7 on 2021-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0019_maintenance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='fromMonth',
            field=models.CharField(default='--', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='toMonth',
            field=models.CharField(default='--', max_length=20),
        ),
    ]
