# Generated by Django 3.1.7 on 2021-04-22 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0021_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='homeNo',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='mem_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.member'),
        ),
    ]
