# Generated by Django 3.1.7 on 2021-04-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0022_auto_20210422_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='mem_id',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='homeNo',
            field=models.CharField(default='XXX', max_length=20),
        ),
    ]
