# Generated by Django 3.1.7 on 2021-04-22 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0023_auto_20210422_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='maintenance_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.maintenance'),
        ),
    ]
